// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCKK_nEJOQ937ZIoKgp8up7jKf1bNLo1U',
    appId: '1:196531323719:web:c8de3312bf02efd1250262',
    messagingSenderId: '196531323719',
    projectId: 'paw-fect-beac4',
    authDomain: 'paw-fect-beac4.firebaseapp.com',
    storageBucket: 'paw-fect-beac4.firebasestorage.app',
    measurementId: 'G-960L8E6FH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcaKXgbuPiFBQd7YRvCNHyWc7QjX4igs',
    appId: '1:196531323719:android:de4a1012f2f15f43250262',
    messagingSenderId: '196531323719',
    projectId: 'paw-fect-beac4',
    storageBucket: 'paw-fect-beac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Bb2QC4F8CUTACKKZfqMX28857NIpQJw',
    appId: '1:196531323719:ios:494a31d04c6c4da9250262',
    messagingSenderId: '196531323719',
    projectId: 'paw-fect-beac4',
    storageBucket: 'paw-fect-beac4.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Bb2QC4F8CUTACKKZfqMX28857NIpQJw',
    appId: '1:196531323719:ios:494a31d04c6c4da9250262',
    messagingSenderId: '196531323719',
    projectId: 'paw-fect-beac4',
    storageBucket: 'paw-fect-beac4.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCKK_nEJOQ937ZIoKgp8up7jKf1bNLo1U',
    appId: '1:196531323719:web:41273859e874b31e250262',
    messagingSenderId: '196531323719',
    projectId: 'paw-fect-beac4',
    authDomain: 'paw-fect-beac4.firebaseapp.com',
    storageBucket: 'paw-fect-beac4.firebasestorage.app',
    measurementId: 'G-TRVC34Y4E6',
  );
}
